### ISSUE TITLE
Keep getting error

### ISSUE THREAD

**Issue by Maxbrick** [bradenmcd/friidump#11]
I keep getting this error when i run the command to rip the wii game: friidump: error while loading shared libraries: libfriidump.so: cannot open shared object file: No such file or directory

Any idea how to fix?

**Comment by gertoe** [comment]
Did you try executing friidump with LD_PRELOAD=path/to/your/libfriidump.so as a temporary workaround yet?

**Comment by Maxbrick** [comment]
thanks, it worked
